services:
  valkey:
    image: docker.io/valkey/valkey:alpine
    container_name: valkey-server
    command: valkey-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    # environment:
    volumes:
      - valkey-data:/data

volumes:
  valkey-data:
