services:
  db:
    image: postgres
    restart: no
    # set shared memory limit when using docker compose.
    shm_size: 128mb
    env_file:
      - path: ../../.env
        required: true
    environment:
      - POSTGRES_DB=postre_data
      # This will be used for write-access to the DB.
      - POSTGRES_USER=postre_admin
    # POSTGRES_PASSWORD should be set in the envvars/.env file.
    # You should also override the readonly password in .env.
    # - POSTGRES_READONLY_PASSWORD=passwd
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./create-readonly-user.sh:/docker-entrypoint-initdb.d/create-readonly-user.sh
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: no
    ports:
      - 8081:8080
volumes:
  postgres_data: